### ISSUE TITLE
Verify usage

### ISSUE THREAD

**Issue by hannesa2** [lorenzodonini/netmic#1]
Concerning this line on macOS

> On macOS, you might have to install pyaudio with a tweak:
> `pip install --global-option='build_ext' --global-option='-I/usr/local/include' --global-option='-L/usr/local/lib' pyaudio`

my output was this

<img width="1457" alt="image" src="https://user-images.githubusercontent.com/3314607/84735910-edf56080-afa4-11ea-97f7-a3144ac83a63.png">

I guess, it's pointless ?

**Comment by lorenzodonini** [comment]
If it worked for you out-of-the-box, all the better 😄 

I personally had an issue on this setup:
- macOS 10.15.5
- Python 3.7.3
- pip 19.0.3
- portaudio 19.6.0

Running just `pip install pyaudio` was throwing an error, saying it couldn't find the `portaudio.h` file.

The solution mentioned in the README is credited to [this article](https://medium.com/@wagnernoise/installing-pyaudio-on-macos-9a5557176c4d) and is optional for that reason.

I guess it makes sense to keep the info there for documentation purposes (and to avoid an additional search).
